name: 'Git Info Action'
description: "Retreive info from git that isn't normally available"
inputs:
  path:
    description: "directory of the repository"
    required: true
    default: "."
  fromMakefile:
    description: "whether to get the tag out of a Makefile"
    required: true
    default: "false"
outputs:
  tag:
    description: "tags used by docker"
    value: ${{ steps.gitinfo.outputs.tag }}
runs:
  using: "composite"
  steps:
    - name: "Get Info"
      id: gitinfo
      shell: bash
      run: |
        if [[ ${{ inputs.fromMakefile }} = "true" ]]
        then
          make get-tag
        else
          cd ${{ inputs.path }}
          git fetch --prune --unshallow --tags -f
          tag=$( if git describe > /dev/null 2>&1 ; then   git describe; else   git rev-parse --short HEAD; fi )
          echo TAG: ${tag}
          echo ::set-output name=tag::${tag}
        fi
