name: 'Ansible Deploy'
description: "Limited Deployment via Ansible"
inputs:
  aws-profile:
    description: 'AWS PROFILE'
    required: true
    default: 'aws'
  path:
    description: 'Ansible Repoistory Path'
    required: true
    default: 'ansible'
  playbook:
    description: 'Ansible Playbook'
    required: true
    default: 'apps.yml'
  stage:
    description: 'Envivonment/Stage to deploy'
    required: true
  repo:
    description: 'Deployment Repository Name'
    required: true
  tag:
    description: 'Tag/image to deploy'
    required: true
  secret:
    description: 'Ansible Vault Secret'
    required: true
  vault-secret-file:
    description: 'Ansible Vault Secret file'
    required: true
    default: ansible/.secret/default
runs:
  using: "composite"
  steps: 
    - name: Ansible Deploy
      shell: bash
      run: | 
        pwd
        mkdir -p $(dirname ${{ inputs.vault-secret-file }})
        echo ${{ inputs.secret }} > ${{ inputs.vault-secret-file }}
        chmod 600 ${{ inputs.vault-secret-file }}
        cat ${{ inputs.vault-secret-file }}
        ls -al ${{ inputs.path }}
        git status
        cd ${{ inputs.path }}
        AWS_PROFILE=${{ inputs.aws-profile }} ansible-playbook -l ${{ inputs.stage }} -t ${{ inputs.tag }} -CD ${{ inputs.playbook }}
