name: 'Ansible Deploy'
description: "Limited Deployment via Ansible"
inputs:
  aws-profile:
    description: 'AWS Profile'
    required: true
    default: 'aws'
  path:
    description: 'Ansible Repoistory Path'
    required: true
    default: 'ansible'
  playbook:
    description: 'Ansible Playbook'
    required: true
    default: 'apps.yml'
  repo:
    description: 'Deployment Repository Name'
    required: true
  stage:
    description: 'Envivonment/Stage to deploy'
    required: true
  name:
    description: 'tag/image version to deploy'
    required: true
  secret:
    description: 'Ansible Vault Secret'
    required: true
  vault-secret-file:
    description: 'Ansible Vault Secret file'
    required: true
    default: .secret/default
  version:
    description: 'tag/image version to deploy'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Ansible Deploy
      shell: bash
      run: | 
        cd ${{ inputs.path }}
        mkdir -p $(dirname ${{ inputs.vault-secret-file }})
        echo ${{ inputs.secret }} > ${{ inputs.vault-secret-file }}
        chmod 600 ${{ inputs.vault-secret-file }}
        sed -i -e 's/  \(${{ inputs.name }}\): .*$/  \1: ${{ inputs.version }}/' group_vars/${{ inputs.stage }}/tags.yml
        CMD='ansible-playbook -l ${{ inputs.stage }} -t aws,${{ inputs.name }}_cicd ${{ inputs.playbook }}'
        echo
        echo "===================================================================="
        echo $CMD
        echo "===================================================================="
        AWS_PROFILE=${{ inputs.aws-profile }} $CMD
