name: 'Ansible Deploy'
description: "Limited Deployment via Ansible"
inputs:
  aws-profile:
    description: 'AWS Profile'
    required: true
    default: 'aws'
  path:
    description: 'Ansible Repoistory Path'
    required: true
    default: 'ansible'
  playbook:
    description: 'Ansible Playbook'
    required: true
    default: 'apps.yml'
  repo:
    description: 'Deployment Repository Name'
    required: true
  stage:
    description: 'Envivonment/Stage to deploy'
    required: true
  tag:
    description: 'Tag/image to deploy'
    required: true
  secret:
    description: 'Ansible Vault Secret'
    required: true
  vault-secret-file:
    description: 'Ansible Vault Secret file'
    required: true
    default: .secret/default
runs:
  using: "composite"
  steps: 
    - name: Ansible Deploy
      shell: bash
      run: | 
        ls -l ~/.ssh
        cat ~/.aws/credentials
        cat ~/.ssh/config
        md5sum ~/.ssh/nrw.pem
        cd ${{ inputs.path }}
        mkdir -p $(dirname ${{ inputs.vault-secret-file }})
        echo ${{ inputs.secret }} > ${{ inputs.vault-secret-file }}
        chmod 600 ${{ inputs.vault-secret-file }}
        AWS_PROFILE=${{ inputs.aws-profile }} ansible-playbook -l ${{ inputs.stage }} -t ${{ inputs.tag }}_cicd,aws -CD ${{ inputs.playbook }}
