name: 'Package JSON'
description: "Retreive info from package.json"
inputs:
  file:
    description: "package.json file"
    required: true
    default: "package.json"
outputs:
  version:
    description: "version"
    value: ${{ steps.package.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: "Get Version"
      id: package
      shell: bash
      run: |
        jq -r '. | "version="+.version' ${{ inputs.file }} >> $GITHUB_OUTPUT
