name: 'Install Ansible'
description: "Install Ansible"
runs:
  using: "composite"
  steps: 
    - name: Ansible
      shell: bash
      run: | 
        sudo apt-get install ansible

    - name: Python Modules
      shell: bash
      run: | 
        python -m pip install --upgrade pip
        pip install botocore boto
