name: 'Install Ansible'
description: "Install Ansible"
inputs:
  aws-profile:
    description: 'AWS PROFILE'
    required: true
    default: 'aws'
  aws-access-key-id:
    description: 'AWS ACCESS KEY ID'
    required: true
  aws-secret-access-key:
    description: 'AWS SECRET ACCESS KEY'
    required: true
  aws-region:
    description: 'AWS region of ECR'
    required: true
    default: 'eu-west-1'
  host-prefix:
    description: 'Hostname prefix'
    required: true
  ssh-key:
    description: 'SSH KEY'
    required: true
runs:
  using: "composite"
  steps: 
    - name: AWS Credentials
      shell: bash
      run: | 
        mkdir ~/.aws
        echo "[${{ inputs.aws-profile }}]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ inputs.aws_access_key_id}}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ inputs.aws_secret_access_key }}" >> ~/.aws/credentials
        echo "region=${{ inputs.aws_region }}" >> ~/.aws/credentials
        chmod 600 ~/.aws/credentials
        cat ~/.aws/credentials
    - name: SSH
      shell: bash
      run: | 
        mkdir ~/.ssh
        echo "StrictHostKeyChecking no" > ~/.ssh/config
        echo "Host ${ inputshost_prefix }}_bastion" >> ~/.ssh/config
        echo "User ec2-user" >> ~/.ssh/config
        echo "    IdentityFile ~/.ssh/bastion" >> ~/.ssh/config
        echo "    hostname %h.epimorphics.net" >> ~/.ssh/config
        echo "  Host ${{ inputshost_prefix }}* 10.*" >> ~/.ssh/config
        echo "    User ec2-user" >> ~/.ssh/config
        echo "    IdentityFile ~/.ssh/bastion" >> ~/.ssh/config
        echo "    ProxyJump ${{ inputs.host_prefix }}-bastion" >> ~/.ssh/config
        chmod 600 ~/.ssh/config
        echo "${{ inputs.ssh_key }}" > ~/.ssh/bastion
        chmod 600 ~/.ssh/bastion
        cat ~/.sss/config
    - name: Ansible
      shell: bash
      run: | 
        sudo apt-get install ansible
    - name: Python Modules
      shell: bash
      run: | 
        python -m pip install --upgrade pip
        pip install boto
