name: 'Mapper'
description: 'Map a pushed git ref to a image specification'
inputs:
  ref:
    description: 'git ref to map'
    required: true
  mapFile:
    description: 'The configuration file'
    required: true
    default: 'deployment.yaml'
outputs:
  image:
    description: name of environment-specific image to build
  target:
    description: name of the target enviroment
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ref }}
    - ${{ inputs.mapFile }}
