name: 'Mapper'
description: 'Map a pushed git ref to a image specification'
inputs:
  ref:
    description: 'git ref to map'
    required: true
  mapFile:
    description: 'The configuration file'
    required: true
    default: 'deployment.yaml'
outputs:
  image:
    description: name of environment-specific image to build
    value: ${{ steps.mapper.outputs.image }}
  target:
    description: name of the target deployment
    value: ${{ steps.mapper.outputs.target }}
  env:
    description: name of the deployment enviroment
    value: ${{ steps.mapper.outputs.env }}
  ecr:
    description: name of the deployment ECR
    value: ${{ steps.mapper.outputs.ecr }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  id: mapper
  args:
    - ${{ inputs.ref }}
    - ${{ inputs.mapFile }}
