name: 'Mapper'
description: 'Map a pushed git ref to a image specification'
inputs:
  ref:
    description: 'git ref to map'
    required: true
  mapFile:
    description: 'The configuration file'
    required: true
    default: 'deployment.yaml'
outputs:
  image:
    description: name of environment-specific image to build
  key:
    description: the name used by ansible to deploy appropriate components
  target:
    description: name of the target deployment
  deploy:
    description: name of the deployment enviroment
  publish:
    description: name of the deployment ECR
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ref }}
    - ${{ inputs.mapFile }}
    - "| tee -a ${GITHUB_OUTPUT}"
